Retroactively commited version from 2008-05-24 12:46

diff --git a/btex b/btex
--- a/btex
+++ b/btex
@@ -3,6 +3,7 @@
 ###   This program is used to  compile latex files and output ps/pdf files  ###
 
         ###                     Changelog                         ###
+        # 04/21/2008    Support for bibtex, slight reorganization   #
         # 03/31/2008    Enabled inverse search for all latex files  #
         #               through the -src-specials command option    #
         #               This means that srcltx is not reqd. now     # 
@@ -46,39 +47,10 @@
         # file changes  --- DONE!                                   #
         #-----------------------------------------------------------#
 
-###   Set the colors that will be used   ### {{{
-yellow="\E[1;33m"
-red="\E[1;31m"
-green="\E[1;32m"
-blue="\E[1;34m"
-underline="\E[4m"
-bold="\E[1m"
-normal="\E[0m"
+. `which my_bash_functions`
 
-
-# Print out information.
-# Usage: info "Whatever you want to print"
-info(){
-    echo -e "  $yellow *$normal   ${@}";
-}
-
-# Print out information without ending with a newline. This adds a space at end
-# Usage: infon "Whatever you want to print"
-infon(){
-    echo -ne "  $yellow *$normal   ${@} ";
-}
-
-# Print out error information.
-# Usage: Err "Whatever you want to print"
-Err(){
-    echo -e "  $red *$normal   [$red ERROR!!$normal ] ${@}" >&2;
-}
-
-die() {
-    Err "$@";
-    exit 1;
-}
-# }}}
+# Source the readfilename
+. `which my_read_files`
 
 check() {
     local INFO=die;
@@ -90,192 +62,67 @@ check() {
     return 0;
 }
     
-DVIPS_PAPER_OPTIONS="-tletter";
+PAPER=letter;
+DVIPS_PAPER_OPTIONS="-t$PAPER";
 check gv && PS_VIEWER="$CHECKED -watch -spartan"
 check xdvi && DVI_VIEWER="$CHECKED"
 check xpdf && PDF_VIEWER="$CHECKED"
 gvim_server=;
 RECURSIVE=0;
-NON_STOP=;
+# By default use non-stop mode, i.e. script will not exit on latex error
+NON_STOP=1; 
 QUIET=;
 COUNT=1;
 INVERSE_SEARCH=;
+XPDF_OPTIONS=;
 # Possible modes: PS2PDF, POSTSCRIPT, ASK_POSTSCRIPT, NO_POSTSCRIPT, PDF
 # Default is below
 MODE="ASK_POSTSCRIPT"; 
 
 help(){ #{{{
     echo;
-    echo -e "  $yellow $( basename ${0} ):$normal";
+    echo -e " $yellow $( basename ${0} ):$normal";
     info "This program is used to compile latex files and output ps/pdf files"
     info "Usage:     $( basename ${0} ) [<options>] [<filename>.tex]";
-    info "Options:"
-    info "-a | --acroread        Use acrobat reader as pdf viewer in lieu of xpdf"
-    info "-b | --beamer          Beamer mode: disable $DVIPS_PAPER_OPTIONS option in dvips"
-    info "-d | --pdf             Output a pdf file,- this uses pdflatex";
-    info "-h | --help            This help text";
-    info "-i | --inv-search      Enable inverse search in dvi";
-    info "-n | --no-postscript   Do not output postscript file";
-    info "-nc| --no-color        Do not use color in output";
-    info "-ns| --non-stop        Do not exit program even if latex gives errors"
-    info "-p | --postscript      Assume \"yes\" for postscript output";
-    info "-pd| --ps2pdf          Generate pdf from postscript output";
-    info "-q | --quiet           Do not print all the output latex spews out"
-    info "-r | --recursive       Recursively compile the source. Otherwise
-                              the program will compile once and exit";
+    info "Options:
+    -a | --acroread       Use acrobat reader as pdf viewer in lieu of xpdf
+    -b | --beamer         Toggle beamer mode: disable $DVIPS_PAPER_OPTIONS option in dvips
+    -B | --bibtex         Enable bibtex compilation
+    -d | --pdf            Output a pdf file,- this uses pdflatex
+    -h | --help           This help text
+    -i | --inv-search     Enable inverse search in dvi
+    -n | --no-postscript  Output only dvi file
+    -nc| --no-color       Do not use color in output
+    -p | --postscript     Run dvips automatically, providing ps output
+    -pd| --ps2pdf         Generate pdf from postscript output
+    -q | --quiet          Do not print all the output latex spews out
+    -r | --recursive      Recursively compile the source. Otherwise
+                          the program will compile once and exit
+    -s | --stop           Exit script if latex gives errors
+    -t <paper type>       Run dvips with -t<paper type> option.
+                          Default paper type used is ${bold}letter${normal}"
     echo;
     info "${bold}Inverse search:$normal
-      - Inverse search is the feature by which one can access the
-        corresponding line in an editor by clicking in the viewer (used to
-        view the latex output).
-      - In this script, inverse search feature can be used if one is using
-        gvim and the tex file is open in a gvim editor. The script
-        automatically determines the correct gvim if multiple gvims are running.
-      - The dvi viewer which is automatically set up by this script is xdvi.
-        Other dvi viewers will need to be configured separately.
-      - If you use okular, then inverse search may be possible even in 
-        pdf files." 
+    - Inverse search is the feature by which one can access the
+      corresponding line in an editor by clicking in the viewer (used to
+      view the latex output).
+    - In this script, inverse search feature can be used if one is using
+      gvim and the tex file is open in a gvim editor. The script
+      automatically determines the correct gvim if multiple gvims are running.
+    - The dvi viewer which is automatically set up by this script is xdvi.
+      Other dvi viewers will need to be configured separately.
+    - If you use okular, then inverse search may be possible even in 
+      pdf files." 
     echo;
-    info "If multiple -d,-n,-p,-pd are given then the last one will be used";
+    info "If multiple -d,-n,-p,-pd are given then the last one will be used"
     echo;
     info "If no filename is given, then an interactive input prompt is provided
     ${underline}An example, when using beamer${normal}:
-    btex -b -d -r -q -ns # recursive, quiet, nonstop, using pdflatex & beamer";
+    btex -b -d -r -q    # recursive, quiet, using pdflatex & beamer"
     echo;
 } #}}}
 
 
-help_read_filename() { #{{{
-    info "readfilename -h|--help: == help!!"
-    info "readfilename <0|1> [<suffix>]"
-    info "${red}BUG!${normal} If a dir is named foo and a file is named fool.bar, then you can enter foo by typing 'foo/.'"
-    info "I know how to fix this bug, but it renders the code clumsy and so I won't do it ;)"
-    info "Examples of Usage:"
-    info "Eg. readfilename 1 tex  == match .tex files in any directory"
-    info "Eg. readfilename 0 tex  == match .tex files in current directory only"
-    info "Eg. readfilename 0      == match any file in current directory only"
-}
-
-## Usage read_filename <0|1> [<suffix>]  -- example: read_filename 1 ogg
-read_filename() {
-    
-    [[ $# -eq 0 ]] && help_read_filename && exit 1;
-
-    ## Declare the following variables
-    local filename;
-    local INPUT_X;
-    local INPUT;
-    global FILEPATH;
-    local SUFFIX;
-    ## Indicate whether we are recursing through directories
-    local DIR=$1;
-    [[ $# -eq 2 ]] && SUFFIX=".$2" || SUFFIX="";
-
-    ## Remember the old pwd:
-    local OLD_PWD=`pwd`
-    
-
-  ## Start of outer loop
-  while [[ -z $filename || -d $filename ]];
-  do
-    [[ -d $filename ]] && cd $filename;
-
-
-    ## Reinitialize all of these to null
-    filename="";
-    INPUT_X=;
-    INPUT=;
-
-    ## clear the screen -- the magic begins from here :)
-    clear;
-    
-    ## Initial list of the file names found
-    find ${INPUT_X}*${SUFFIX} -maxdepth 0 -type f -print 2>/dev/null  
-
-    ## Initial list of directories + good looking output
-    echo -ne "\n\n-----^^^^${green}Possible files$normal^^^^-----\n\n"
-    [[ $DIR -eq 1 ]] && find ${INPUT_X}* -maxdepth 0 -type d -printf "%f\t\t" 2>/dev/null && \
-    echo -e "\n\n-----^^^^${yellow}Possible directories${normal}^^^^-----\n\n"
-    
-    
-    ## Do the loop until complete
-    while true
-    do
-        # black on green  -- for completion part
-        if [[ ! -z "$INPUT_X" ]]; then
-            echo -ne "  $yellow *$normal   Enter the filename [${INPUT_X}\033[00;30;42m${EXT}$normal ?]: ${INPUT_X}"
-        elif [[ $DIR -eq 1 ]]; then
-            infon "Enter the filename (use .. to go up one directory):"
-        else
-            infon "Enter the filename:"
-        fi
-
-        ## Read each character as it is typed
-        read -n 1 INPUT
-
-        ## If input is null, then complete the rest of the stuff and dump it into $filename and exit from this loop
-        if [[ -z "$INPUT" && ! -z "$INPUT_X" ]]; then
-            filename="${INPUT_X}${EXT}";
-            break;
-        elif [[ -z "$INPUT" && -z "$INPUT_X" ]]; then
-            Err "No filename provided";
-            #help_read_filename;
-            exit 1;
-        fi
-
-        ## else clear the screen for the next best matches
-        clear;
-
-        ## Whenever you press a backspace, it sends a non-printable character
-        ## delete doesn't work since it sends three (!!) characters and read takes in only one
-        if [[ -z `echo -e "$INPUT" | egrep  "[[:print:]]"` ]]; then
-            ## If backspace was sent, delete the previous character
-            INPUT_X=`echo ${INPUT_X} | head -c -2`
-        else
-            ## else append the current character to the extended input variable, $INPUT_X
-            INPUT_X="${INPUT_X}${INPUT}"
-        fi
-
-
-        ## If the DIR variable is turned on, and we received a .., then go up one directory
-        [[ $DIR -eq 1 && "$INPUT_X" = ".." ]] && cd .. && INPUT_X="" && FILEPATH=`pwd`;
-
-
-        ## Find all the best matches to files and output them
-        OUTPUT=`find ${INPUT_X}* -maxdepth 0 -type f -print 2>/dev/null | egrep "${SUFFIX}$"`;
-        echo "${OUTPUT}"
-
-
-        ## If the extended input is non-zero, then we need to find the extension to it.
-        if [[ ! -z "${INPUT_X}" ]]; then
-            ## If there are no matching files, and DIR is on, then complete dirs instead of files
-            if [[ -z "${OUTPUT}" && $DIR -eq 1 ]]; then
-                EXT=`find ${INPUT_X}* -maxdepth 0 -type d -print 2>/dev/null | sed -ne "1s:^${INPUT_X}\(.*\)$:\1:p"`
-            else
-                EXT=`echo "${OUTPUT}" | sed -ne "1s:^${INPUT_X}\(.*\)$:\1:p"`;
-            fi
-        fi
-
-        ## Again need for some nicely formatted output
-        echo -ne "\n\n-----^^^^${green}Possible files$normal^^^^-----\n\n"
-        [[ $DIR -eq 1 ]] && find ${INPUT_X}* -maxdepth 0 -type d -printf "%f\t\t" 2>/dev/null && \
-        echo -e "\n\n-----^^^^${yellow}Possible directories${normal}^^^^-----\n\n"
-        
-    done
-
-    ## Completed inner loop, so $filename is either null or has some info in it.
-    if [[ -z $FILEPATH ]]; then
-        FILEPATH="$filename"
-    else
-        FILEPATH="$FILEPATH/$filename"
-    fi
-  done
-  ## Completed outer loop here
-
-    ## Return to the dir from which this function was called
-    cd "$OLD_PWD"
-
-} #}}}
 
 
 set_xdvi() { # {{{
@@ -302,23 +149,38 @@ set_xdvi() { # {{{
 }
 # }}}
 
+set_beamer_options() {
+    if [[ $DVIPS_PAPER_OPTIONS ]]; then
+        DVIPS_PAPER_OPTIONS="";
+        [[ $PDF_VIEWER = *xpdf ]] && XPDF_OPTIONS="-z 200";
+    else
+        DVIPS_PAPER_OPTIONS="-t$PAPER";
+        [[ $PDF_VIEWER = *xpdf ]] && XPDF_OPTIONS=;
+    fi
+}
+
 #echo $-
-[[ $DISPLAY && -z "$@" ]] && ! tty -s && ( xterm -hold -e $0 -h && exit )
+if [[ $DISPLAY && -z "$@" ]] && ! tty -s; then 
+    xterm -hold -e $0 -h; exit
+fi
 
 until [[ -z "$1" ]]; do
     case $1 in
+    -a | --acroread)    check acroread && PDF_VIEWER="$CHECKED";;
+    -b | --beamer)      set_beamer_options;;
+    -B | --bibtex)      check bibtex && BIBTEX=1;;
+    -d | --pdf)         MODE="PDF";;
     -h | --help)        help; exit; ;;
+    -i | --inv-search)  INVERSE_SEARCH="-src-specials";;
+    -n | --no-postscript) MODE="NO_POSTSCRIPT";;
     -nc| --no-color)    unset yellow red green underline bold; ;;
-    -ns| --non-stop)    NON_STOP=1; ;;
     -p | --postscript)  MODE="POSTSCRIPT";;
     -pd| --ps2pdf)      MODE="PS2PDF";;
-    -n | --no-postscript) MODE="NO_POSTSCRIPT";;
-    -d | --pdf)         MODE="PDF";;
-    -r | --recursive)   RECURSIVE=1; ;;
-    -b | --beamer)      DVIPS_PAPER_OPTIONS="";; 
-    -a | --acroread)    check acroread && PDF_VIEWER="$CHECKED";;
     -q | --quiet)       QUIET=1;;
-    -i | --inv-search)  INVERSE_SEARCH="-src-specials";;
+    -r | --recursive)   RECURSIVE=1; ;;
+    -s | --stop)        unset NON_STOP ;;
+    -t) [[ $2 = -* ]] && die "$2: Invalid paper type to -t option";
+        PAPER=$2; DVIPS_PAPER_OPTIONS=-t$PAPER; shift;;
     -*) help; die "${red}$1${normal}: Invalid Option!\n"; ;;
     *)  filename="$1"; ;;
     esac
@@ -336,7 +198,11 @@ show_menu() { # {{{
         PS2PDF)         echo -ne "\tPDF file is generated from PS, using ps2pdf";;
         PDF)            echo -ne "\tPDF file is generated using pdflatex";;
     esac
-    ([[ $INVERSE_SEARCH ]] && echo -e "\n\t\t\tInverse search is enabled" ) || echo;
+    [[ $INVERSE_SEARCH ]] && echo -ne "\n\t\t\tInverse search is enabled"
+    [[ $BIBTEX ]] && echo -ne "\n\t\t\tBibtex compilation is enabled"
+    [[ $QUIET ]] && echo -ne "\n\t\t\tQuiet mode is enabled"
+    [[ $DVIPS_PAPER_OPTIONS ]] || echo -ne "\n\t\t\tBeamer mode is enabled"
+    echo;
     infon "Want to continue with another compile?\n
 \tEnter/${green}Y${normal}: Yes (Repeat compile)\t\
 ${green}N${normal}: No (Quit)\n\t\
@@ -347,9 +213,11 @@ ${green}X${normal}: Launch ${DVI_VIEWER}\n\t\
 ${green}2${normal}: Toggle PS to PDF output\t\
 ${green}F${normal}: Launch ${PDF_VIEWER}\n\t\
 ${green}Q${normal}: Toggle Quiet mode\t\t\
-${green}I${normal}: Toggle Inverse search\n"
+${green}I${normal}: Toggle Inverse search\n\t\
+${green}E${normal}: Toggle Beamer mode\n\t\
+${green}B${normal}: Toggle Bibtex compilation"
     [[ $INOTIFYWAIT ]] && echo -ne "\t${green}A${normal}: Enable Autocompile mode\n"
-    infon "Give an option ([Y]/N/P/D/L/X/Q/A):"
+    infon "Give an option (2/A/B/D/E/F/I/L/N/P/Q/X/[Y]):"
 }
 # }}}
 
@@ -358,16 +226,50 @@ success() {
         echo -e "${green}Done!${normal}";
 }
 
-compile_ps() { #{{{
+run_bibtex() { # {{{
+    if [[ $QUIET ]]; then
+        bibtex --terse $file
+        [[ $? -ne 0 && -z $NON_STOP ]] && die "$filename: bibtex failed";
+    else
+        bibtex $file
+        [[ $? -ne 0 && -z $NON_STOP ]] && die "$filename: bibtex failed";
+    fi
+} # }}}
+
+run_latex() { # {{{
+    local status;
     if [[ $QUIET ]]; then
         latex $INVERSE_SEARCH "${filename}"  >&1 | grep --color -A 11 '^! .*';
         # echo ${PIPESTATUS[@]} gives the exit status of each part of pipe
-        [[ ${PIPESTATUS[0]} -ne 0 && -z "$NON_STOP" ]] && \
-            die "${filename}: Error in latex compilation"; 
+        status=${PIPESTATUS[0]};
     else
         latex $INVERSE_SEARCH "${filename}"
-        [[ $? -ne 0 && -z "$NON_STOP" ]] && \
-            die "${filename}: Error in latex compilation"; 
+        status=$?
+    fi
+    [[ $status -ne 0 && -z $NON_STOP ]] && \
+        die "${filename}: Error in latex compilation" || \
+        return $status
+} # }}}
+
+run_pdflatex() { # {{{
+    local status;
+    if [[ "$QUIET" ]]; then
+        pdflatex $INVERSE_SEARCH "${filename}" >&1 | grep --color -A 11 '^! .*' -;
+        # echo ${PIPESTATUS[@]} gives the exit status of each part of pipe
+        status=${PIPESTATUS[0]};
+    else
+        pdflatex $INVERSE_SEARCH "$filename"
+        status=$?
+    fi
+    [[ $status -ne 0 && -z $NON_STOP ]] && \
+        die "${filename}: pdflatex compilation failed" || \
+        return $status
+} # }}}
+
+compile_ps() { #{{{
+    run_latex || return
+    if [[ $BIBTEX ]]; then
+        run_bibtex; run_latex; run_latex;
     fi
 
     case $1 in
@@ -393,15 +295,9 @@ compile_pdf() { # {{{
             success $?
         fi
     done
-    if [[ "$QUIET" ]]; then
-        pdflatex $INVERSE_SEARCH "${filename}" >&1 | grep --color -A 11 '^! .*' -;
-        # echo ${PIPESTATUS[@]} gives the exit status of each part of pipe
-        [[ ${PIPESTATUS[0]} -ne 0 && -z $NON_STOP ]] && \
-            die "${filename}: pdflatex compilation failed"
-    else
-        pdflatex $INVERSE_SEARCH "$filename"
-        [[ $? -ne 0 && -z $NON_STOP ]] && \
-            die "${filename}: pdflatex compilation failed"
+    run_pdflatex || return
+    if [[ $BIBTEX ]]; then
+        run_bibtex; run_pdflatex; run_pdflatex;
     fi
 }
 # }}}
@@ -490,6 +386,10 @@ while true; do
             infon "No. of secs of wait-time before autocompile aborts [default: 300]:"
             read WAITTIME; [[ $WAITTIME && $WAITTIME -ge 0 ]] || WAITTIME=300;
             autocompile $MODE $answer;;
+    [bB])   if [[ -z $BIBTEX ]]; then
+                check bibtex && BIBTEX=1;
+            else unset BIBTEX;
+            fi;;
     [dD])   if [[ "$MODE" = "PDF" ]]; then
                 MODE="ASK_POSTSCRIPT"; 
                 info "Pdf file will not be generated"; sleep 1.5;
@@ -499,7 +399,8 @@ while true; do
                 info "Pdf file will be generated using pdflatex"; sleep 1.5;
                 compile $MODE;
             fi ;;
-    [fF])   $PDF_VIEWER $file.pdf >&/dev/null & ;;
+    [eE])   set_beamer_options;;
+    [fF])   $PDF_VIEWER $XPDF_OPTIONS $file.pdf >&/dev/null & ;;
     [lLoO]) if [[ -f "$file.ps" ]]; then 
                 $PS_VIEWER $file.ps 2>/dev/null &
                 [[ $? -ne 0 ]] && Err "Error in launching ${PS_VIEWER%%\ *}";
@@ -527,7 +428,7 @@ while true; do
                 info "Postscript file will be automatically generated"; sleep 1.5;
                 compile $MODE
             fi ;;
-    [qQ])   if [[ $QUIET ]]; then QUIET=""; echo;
+    [qQ])   if [[ $QUIET ]]; then QUIET=; echo;
                 info "Quiet mode ${bold}disabled${normal}";
             else QUIET=1; echo; info "Quiet mode ${bold}enabled${normal}";
             fi ;;
