Retroactively commited version from 2008-04-10 05:57

diff --git a/btex b/btex
--- a/btex
+++ b/btex
@@ -3,6 +3,18 @@
 ###   This program is used to  compile latex files and output ps/pdf files  ###
 
         ###                     Changelog                         ###
+        # 03/31/2008    Enabled inverse search for all latex files  #
+        #               through the -src-specials command option    #
+        #               This means that srcltx is not reqd. now     # 
+        #               Rewrote help and provided command line opt. #
+        # 02/28/2008    Fixed bugs in set_xdvi which was being used #
+        #               to enable inverse search in xdvi            #
+        #               Fixed bugs in autocompile WAITTIME          #
+        #               Disabled autocompile option if inotifywait  #
+        #               is not available                            #
+        # 02/26/2008    Enabled inverse search through xdvi & gvim  #
+        # 12/30/2007    Code rearrangement and                      #
+        #               FULL autocompile mode! :D                   #
         # 12/25/2007    Allow one to execute it by clicking on the  #
         #               file in rox                                 #
         #               Better help text                            #
@@ -31,13 +43,14 @@
         #                                                           #
         # Enable an auto mode, where the latex file will be         #
         # automatically compiled whenever the timestamp of the tex  #
-        # file changes.                                             #
+        # file changes  --- DONE!                                   #
         #-----------------------------------------------------------#
 
 ###   Set the colors that will be used   ### {{{
 yellow="\E[1;33m"
 red="\E[1;31m"
 green="\E[1;32m"
+blue="\E[1;34m"
 underline="\E[4m"
 bold="\E[1m"
 normal="\E[0m"
@@ -67,16 +80,28 @@ die() {
 }
 # }}}
 
+check() {
+    local INFO=die;
+    [[ $2 ]] && INFO=$2;
+    [[ ! -x `which $1 2>/dev/null` ]] && \
+    $INFO "You don't seem to have $1 installed. Is your PATH setup correctly?"\
+    && return 1;
+    CHECKED=`which $1`
+    return 0;
+}
+    
 DVIPS_PAPER_OPTIONS="-tletter";
-PS_VIEWER="gv -watch -spartan"
-DVI_VIEWER="xdvi"
-PDF_VIEWER="xpdf"
+check gv && PS_VIEWER="$CHECKED -watch -spartan"
+check xdvi && DVI_VIEWER="$CHECKED"
+check xpdf && PDF_VIEWER="$CHECKED"
+gvim_server=;
 RECURSIVE=0;
-PREV_MODE=;
 NON_STOP=;
 QUIET=;
 COUNT=1;
-# Possible modes: POSTSCRIPT, ASK_POSTSCRIPT, NO_POSTSCRIPT, PDF : Default is below
+INVERSE_SEARCH=;
+# Possible modes: PS2PDF, POSTSCRIPT, ASK_POSTSCRIPT, NO_POSTSCRIPT, PDF
+# Default is below
 MODE="ASK_POSTSCRIPT"; 
 
 help(){ #{{{
@@ -86,15 +111,32 @@ help(){ #{{{
     info "Usage:     $( basename ${0} ) [<options>] [<filename>.tex]";
     info "Options:"
     info "-a | --acroread        Use acrobat reader as pdf viewer in lieu of xpdf"
-    info "-b | --beamer          Beamer mode: disable -tletter option in dvips"
+    info "-b | --beamer          Beamer mode: disable $DVIPS_PAPER_OPTIONS option in dvips"
     info "-d | --pdf             Output a pdf file,- this uses pdflatex";
     info "-h | --help            This help text";
+    info "-i | --inv-search      Enable inverse search in dvi";
     info "-n | --no-postscript   Do not output postscript file";
     info "-nc| --no-color        Do not use color in output";
     info "-ns| --non-stop        Do not exit program even if latex gives errors"
     info "-p | --postscript      Assume \"yes\" for postscript output";
+    info "-pd| --ps2pdf          Generate pdf from postscript output";
     info "-q | --quiet           Do not print all the output latex spews out"
-    info "-r | --recursive       Recursively compile the source";
+    info "-r | --recursive       Recursively compile the source. Otherwise
+                              the program will compile once and exit";
+    echo;
+    info "${bold}Inverse search:$normal
+      - Inverse search is the feature by which one can access the
+        corresponding line in an editor by clicking in the viewer (used to
+        view the latex output).
+      - In this script, inverse search feature can be used if one is using
+        gvim and the tex file is open in a gvim editor. The script
+        automatically determines the correct gvim if multiple gvims are running.
+      - The dvi viewer which is automatically set up by this script is xdvi.
+        Other dvi viewers will need to be configured separately.
+      - If you use okular, then inverse search may be possible even in 
+        pdf files." 
+    echo;
+    info "If multiple -d,-n,-p,-pd are given then the last one will be used";
     echo;
     info "If no filename is given, then an interactive input prompt is provided
     ${underline}An example, when using beamer${normal}:
@@ -236,52 +278,68 @@ read_filename() {
 } #}}}
 
 
+set_xdvi() { # {{{
+    # Enter gvim --remote here:
+    #   determine if only one gvim is running, if so take that as the remote
+    #   else: check to see if multiple gvim's are running
+    #       if yes: check to see if the $file has servername with its gvim
+    #       else:   discard all lines with servername
+    #               check the order $o of the $file in ps output => GVIM$o
+    #       else:   file is not open, can't do anything.
+    #   else: file is not open, can't do anything.
+    [[ ${DVI_VIEWER/xdvi/} = $DVI_VIEWER ]] && return
+    TMP_FILE=`mktemp`
+    ps -u $USER -o command | grep ^gvim  > $TMP_FILE
 
-check() {
-    [[ ! -x `which $@` ]] && die "You don't seem to have $@ installed. Is your PATH setup correctly?";
-    return 0;
+    if grep "$file" $TMP_FILE | grep -q "\-\-servername"; then
+        gvim_server=`grep "$file" $TMP_FILE | sed -ne "s@^.*\-\-servername \([[:alnum:]]*\) .*$@\1@p"`
+    elif grep -q "$file" $TMP_FILE; then
+        gvim_server=`grep -n "$file" $TMP_FILE`;
+        gvim_server=${gvim_server%%:*};
+        gvim_server=`gvim --serverlist | tail -n +$gvim_server | head -n 1`;
+    fi
+    rm -f $TMP_FILE
 }
-    
+# }}}
+
 #echo $-
 [[ $DISPLAY && -z "$@" ]] && ! tty -s && ( xterm -hold -e $0 -h && exit )
 
-if [[ -n "$@" ]]; then
-    for i in "$@"
-    do
-        case $i in
-        -h | --help)        help; exit; ;;
-        -nc | --no-color)   unset yellow red green underline bold; ;;
-        -ns | --non-stop)   NON_STOP=1; ;;
-        -p | --postscript)
-            if [[ "$MODE" = "NO_POSTSCRIPT" ]]; then 
-                help; die "Can not give -p and -n options together\n";
-            else    MODE="POSTSCRIPT";
-            fi ;;
-        -n | --no-postscript)
-            if [[ "$MODE" = "POSTSCRIPT" ]]; then
-                help; die "Can not give -p and -n options together\n";
-            else    MODE="NO_POSTSCRIPT";
-            fi ;;
-        -d | --pdf)
-            if [[ "$MODE" = "POSTSCRIPT" || "$MODE" = "NO_POSTSCRIPT" ]]; then
-                help;  die "Can not give -p or -n, and -d options together\n";
-            else check pdflatex && check epstopdf; MODE="PDF"
-            fi ;;
-        -r | --recursive)   RECURSIVE=1; ;;
-        -b | --beamer)      DVIPS_PAPER_OPTIONS="";; 
-        -a | --acroread)    PDF_VIEWER="acroread";;
-        -q | --quiet)       QUIET=1;;
-        -*)     help; die "${red}$i${normal}: Invalid Option!\n"; ;;
-        *)      filename="$i"; ;;
-        esac
-    done
-fi
+until [[ -z "$1" ]]; do
+    case $1 in
+    -h | --help)        help; exit; ;;
+    -nc| --no-color)    unset yellow red green underline bold; ;;
+    -ns| --non-stop)    NON_STOP=1; ;;
+    -p | --postscript)  MODE="POSTSCRIPT";;
+    -pd| --ps2pdf)      MODE="PS2PDF";;
+    -n | --no-postscript) MODE="NO_POSTSCRIPT";;
+    -d | --pdf)         MODE="PDF";;
+    -r | --recursive)   RECURSIVE=1; ;;
+    -b | --beamer)      DVIPS_PAPER_OPTIONS="";; 
+    -a | --acroread)    check acroread && PDF_VIEWER="$CHECKED";;
+    -q | --quiet)       QUIET=1;;
+    -i | --inv-search)  INVERSE_SEARCH="-src-specials";;
+    -*) help; die "${red}$1${normal}: Invalid Option!\n"; ;;
+    *)  filename="$1"; ;;
+    esac
+    shift
+done
 
 show_menu() { # {{{
     echo; echo;
-    info "Want to continue with another compile?\n
-\tEnter/${green}Y${normal}: Yes\t\t\t\
-${green}N${normal}: No\n\t\
+
+    infon "${bold}Current mode$normal:${blue}"
+    case $MODE in
+        ASK_POSTSCRIPT) echo -ne "\tPostscript file is generated after confirmation";;
+        NO_POSTSCRIPT)  echo -ne "\tOnly DVI file is generated";;
+        POSTSCRIPT)     echo -ne "\tPostscript file is automatically generated";;
+        PS2PDF)         echo -ne "\tPDF file is generated from PS, using ps2pdf";;
+        PDF)            echo -ne "\tPDF file is generated using pdflatex";;
+    esac
+    ([[ $INVERSE_SEARCH ]] && echo -e "\n\t\t\tInverse search is enabled" ) || echo;
+    infon "Want to continue with another compile?\n
+\tEnter/${green}Y${normal}: Yes (Repeat compile)\t\
+${green}N${normal}: No (Quit)\n\t\
 ${green}P${normal}: Toggle Postscript output\t\
 ${green}L${normal}: Launch ${PS_VIEWER%%\ *}\n\t\
 ${green}D${normal}: Toggle Pdf Output\t\t\
@@ -289,19 +347,25 @@ ${green}X${normal}: Launch ${DVI_VIEWER}\n\t\
 ${green}2${normal}: Toggle PS to PDF output\t\
 ${green}F${normal}: Launch ${PDF_VIEWER}\n\t\
 ${green}Q${normal}: Toggle Quiet mode\t\t\
-${green}A${normal}: Enable Autocompile mode"
+${green}I${normal}: Toggle Inverse search\n"
+    [[ $INOTIFYWAIT ]] && echo -ne "\t${green}A${normal}: Enable Autocompile mode\n"
     infon "Give an option ([Y]/N/P/D/L/X/Q/A):"
 }
 # }}}
 
+success() {
+    ([[ $1 -ne 0 ]] && echo -e "${red}Failed!${normal}") ||\
+        echo -e "${green}Done!${normal}";
+}
+
 compile_ps() { #{{{
     if [[ $QUIET ]]; then
-        latex "${filename}"  >&1 | grep --color -A 11 '^! .*';
+        latex $INVERSE_SEARCH "${filename}"  >&1 | grep --color -A 11 '^! .*';
         # echo ${PIPESTATUS[@]} gives the exit status of each part of pipe
         [[ ${PIPESTATUS[0]} -ne 0 && -z "$NON_STOP" ]] && \
             die "${filename}: Error in latex compilation"; 
     else
-        latex "${filename}"
+        latex $INVERSE_SEARCH "${filename}"
         [[ $? -ne 0 && -z "$NON_STOP" ]] && \
             die "${filename}: Error in latex compilation"; 
     fi
@@ -315,40 +379,72 @@ compile_ps() { #{{{
     case $answer in
         "" | [yY]*) infon "Creating $file.ps ... ";#echo;
             dvips ${DVIPS_PAPER_OPTIONS} -q -o "$file.ps" "$file.dvi"
-            ([[ $? -ne 0 ]] && echo -e "${red}Failed!${normal}") ||\
-                echo -e "${green}Done!${normal}";;
+            success $? ;;
         *) ;; # Do nothing
     esac
 } #}}}
 
 compile_pdf() { # {{{
     info "Converting the (newer) eps images to pdf ..."
-    find *.eps | while read i; do
+    find *.eps 2>/dev/null | while read i; do
         if [[ "${i%\.*}.pdf" -ot "$i" ]]; then
             infon "Converting ${bold}$i${normal} to ${bold}${i%\.*}.pdf${normal} ... "
             epstopdf $i --outfile="${i%\.*}.pdf"
-            ([[ $? -ne 0 ]] && echo -e "${red}Failed!${normal}") ||\
-                echo -e "${green}Done!${normal}"
+            success $?
         fi
     done
     if [[ "$QUIET" ]]; then
-        pdflatex "${filename}" >&1 | grep --color -A 11 '^! .*' -;
+        pdflatex $INVERSE_SEARCH "${filename}" >&1 | grep --color -A 11 '^! .*' -;
         # echo ${PIPESTATUS[@]} gives the exit status of each part of pipe
         [[ ${PIPESTATUS[0]} -ne 0 && -z $NON_STOP ]] && \
             die "${filename}: pdflatex compilation failed"
     else
-        pdflatex "$filename"
+        pdflatex $INVERSE_SEARCH "$filename"
         [[ $? -ne 0 && -z $NON_STOP ]] && \
             die "${filename}: pdflatex compilation failed"
     fi
 }
 # }}}
 
+compile() { # {{{
+    case $1 in
+        ASK_POSTSCRIPT) compile_ps ask ;;
+        POSTSCRIPT)     compile_ps ;;
+        NO_POSTSCRIPT)  compile_ps only_dvi;;
+        PDF)        compile_pdf;;
+        PS2PDF)     compile_ps;
+            infon "Creating $file.pdf from $file.ps ... ";
+            ps2pdf $file.ps
+            success $?;;
+        *)  ;;
+    esac
+} # }}}
+
+autocompile() { # {{{
+    local MODE=$1;
+    local TOTAL=$2;
+    #local WAITTIME=$3;     # WAITTIME should be already set
+    for (( i=1; i<=$TOTAL; i+=1 )); do
+        echo -ne "  ${blue} *   Waiting$normal for change in the status of file ...\r"
+        if $INOTIFYWAIT -t $WAITTIME -qq ${filename}; then
+        # Use above line if you want to break out of autocompile after some
+        # time, say 300s, if no modifications are made for 300s.
+        # Otherwise use following line
+        #if inotifywait -qq ${filename}; then
+            info "Autocompile # $i/$TOTAL                                   "
+            compile $MODE
+        else
+            info "${red}Abort autocompile${normal}: No change in status of file for over $WAITTIME seconds"
+            return
+        fi
+    done
+}
+# }}}
+
 # Some error checking
 check latex;
-[[ "$MODE" = "POSTSCRIPT" || "$MODE" = "ASK_POSTSCRIPT" ]] && check dvips && check "${PS_VIEWER%%\ *}";
-
-
+[[ "$MODE" = "POSTSCRIPT" || "$MODE" = "ASK_POSTSCRIPT" ]] && check dvips;
+[[ "$MODE" = "PDF" ]] && check pdflatex && check epstopdf;
 
 
 if [[ -z ${filename} ]]; then
@@ -366,80 +462,89 @@ fi
 cd "$(dirname "$filename")"
 file="${filename%\.*}";
 
+# Compile the file with command line parameters
+compile $MODE
+[[ $RECURSIVE -eq 0 ]] && exit;
+
+# Set XDVI if possible
+set_xdvi
+
+# Check for the presence of inotifywait
+if check inotifywait Err; then
+    INOTIFYWAIT=$CHECKED;
+else
+    Err "${bold}inotifywait${normal} not found. Autocompile mode will be disabled";
+fi
+
+# Now, enter recursion
 while true; do
-
-    # The autocompile mode is basically a bad hack :(
-    if [[ $MODE = "AUTO_COMPILE" && $PREV_MODE != "AUTO_COMPILE" ]]; then
-        if inotifywait -t 300 -qq ${filename}; then
-            info "Autocompile # $COUNT/5"
-            MODE=$PREV_MODE; PREV_MODE=AUTO_COMPILE;
-        else
-            MODE=NO_COMPILE;
-        fi
-    elif [[ $PREV_MODE = "AUTO_COMPILE" ]]; then
-        MODE=AUTO_COMPILE; PREV_MODE=; COUNT=1;
-    fi
-
-    case $MODE in
-        ASK_POSTSCRIPT) compile_ps ask ;;
-        POSTSCRIPT)     compile_ps ;;
-        NO_POSTSCRIPT)  compile_ps only_dvi;;
-        PDF)            compile_pdf;;
-        NO_COMPILE) MODE=$PREV_MODE; ;;
-        PS2PDF)     compile_ps;
-            infon "Creating $file.pdf from $file.ps ... ";
-            ps2pdf $file.ps
-            ([[ $? -ne 0 ]] && echo -e "${red}Failed!${normal}") ||\
-                echo -e "${green}Done!${normal}" ;;
-        *)  ;;
-    esac
-
-    # The hack to get autocompile mode working continues :(
-    if [[ $PREV_MODE = "AUTO_COMPILE" && $COUNT -lt 5 ]]; then
-        COUNT=$(( $COUNT+1 ));
-        PREV_MODE=$MODE; MODE=AUTO_COMPILE;
-        continue;
-    elif [[ $PREV_MODE = "AUTO_COMPILE" ]]; then
-        continue;
-    fi
-
-    [[ $RECURSIVE -eq 0 ]] && break;
 
     show_menu
     read -n 1 answer; echo;
     case $answer in         # Options arranged alphabetically
-    2)      MODE="PS2PDF";;
-    [aA])   check inotifywait; PREV_MODE=$MODE; MODE=AUTO_COMPILE;
-            info "Autocompile mode ${bold}Enabled${normal}";;
+    2)      MODE="PS2PDF"; compile "PS2PDF";;
+    [aA])   [[ -z $INOTIFYWAIT ]] && check inotifywait && INOTIFYWAIT="$CHECKED"
+            info "Autocompile mode ${bold}Enabled${normal}";
+            infon "No. of times you want to compile automatically [default: 5]:"
+            read answer; [[ $answer -gt 0 ]] || answer=5;
+            infon "No. of secs of wait-time before autocompile aborts [default: 300]:"
+            read WAITTIME; [[ $WAITTIME && $WAITTIME -ge 0 ]] || WAITTIME=300;
+            autocompile $MODE $answer;;
     [dD])   if [[ "$MODE" = "PDF" ]]; then
-                MODE="ASK_POSTSCRIPT"; info "Pdf file will not be generated"; sleep 1.5;
-            else    MODE="PDF"; info "Pdf file will be generated"; sleep 1.5;
+                MODE="ASK_POSTSCRIPT"; 
+                info "Pdf file will not be generated"; sleep 1.5;
+                compile $MODE;
+            else    
+                MODE="PDF";
+                info "Pdf file will be generated using pdflatex"; sleep 1.5;
+                compile $MODE;
             fi ;;
-    [fF])   $PDF_VIEWER $file.pdf >&/dev/null &
-            PREV_MODE=$MODE; MODE=NO_COMPILE; ;;
+    [fF])   $PDF_VIEWER $file.pdf >&/dev/null & ;;
     [lLoO]) if [[ -f "$file.ps" ]]; then 
                 $PS_VIEWER $file.ps 2>/dev/null &
                 [[ $? -ne 0 ]] && Err "Error in launching ${PS_VIEWER%%\ *}";
             else    Err "$file.ps does not exist!";
-            fi 
-            PREV_MODE=$MODE; MODE=NO_COMPILE; ;;
+            fi ;;
+    [iI])   if [[ $INVERSE_SEARCH ]]; then
+                INVERSE_SEARCH=; gvim_server=; echo;
+                info "Disabling inverse search during compilation. Restart ${DVI_VIEWER##*\/}.";
+                sleep 1.5;
+            else
+                INVERSE_SEARCH="-src-specials"; echo;
+                set_xdvi;
+                info "Enabling inverse search during compilation.  Restart ${DVI_VIEWER##*\/}";
+                [[ ${DVI_VIEWER/xdvi/} = $DVI_VIEWER ]] &&\
+                info "You will need to configure ${DVI_VIEWER##*\/} to use this feature";
+                sleep 1.5;
+            fi;;
     [nN])   break; ;;
     [pP])   if [[ "$MODE" = "POSTSCRIPT" || "$MODE" = "ASK_POSTSCRIPT" ]]; then
-                MODE="NO_POSTSCRIPT"; info "Postscript file will not be generated"; sleep 1.5;
-            else    MODE="POSTSCRIPT"; info "Postscript file will be automatically generated"; sleep 1.5;
+                MODE="NO_POSTSCRIPT";
+                info "Postscript file will not be generated"; sleep 1.5;
+                compile $MODE
+            else    
+                MODE="POSTSCRIPT"; 
+                info "Postscript file will be automatically generated"; sleep 1.5;
+                compile $MODE
             fi ;;
     [qQ])   if [[ $QUIET ]]; then QUIET=""; echo;
                 info "Quiet mode ${bold}disabled${normal}";
             else QUIET=1; echo; info "Quiet mode ${bold}enabled${normal}";
-            fi
-            PREV_MODE=$MODE; MODE=NO_COMPILE; ;;
+            fi ;;
     [xX])   if [[ -f "$file.dvi" ]]; then
-                $DVI_VIEWER $file.dvi >& /dev/null & # Don't want error messages to mess up terminal
+                # dvips error messages should not mess up terminal
+                if [[ $gvim_server ]]; then
+                    # gvim_server is nonempty if xdvi is used
+                    $DVI_VIEWER -editor \
+                        "gvim --servername $gvim_server --remote +%l %f" \
+                        $file.dvi >& /dev/null &
+                else
+                    $DVI_VIEWER $file.dvi >& /dev/null &
+                fi
                 [[ $? -ne 0 ]] && Err "Error in launching ${DVI_VIEWER}";
             else    Err "$file.dvi does not exist!";
-            fi
-            PREV_MODE=$MODE; MODE=NO_COMPILE; ;;
-    "" | [yY])  continue; ;;
+            fi ;;
+    "" | [yY])  compile $MODE ;;
     *)      die "$answer: Invalid Option!"; ;;
     esac
 
