Factor out the conversion of eps figures to pdf

diff --git a/btex b/btex
--- a/btex
+++ b/btex
@@ -954,25 +954,7 @@ compile() {
 
 # Usage: compile_pdf
 compile_pdf() {
-    local -i num_newer_eps=0
-    local -i counter=0
-    local f
-    while read f; do
-        if [[ ! -e "${f%\.*}.pdf" || "${f%\.*}.pdf" -ot "$f" ]]; then
-            ((num_newer_eps++))
-        fi
-    done < <(find *.eps 2>/dev/null)
-    [[ $num_newer_eps -gt 0 ]] &&
-        info "Converting $num_newer_eps (newer) eps images to pdf ..."
-    while read f; do
-        if [[ ! -e "${f%\.*}.pdf" || "${f%\.*}.pdf" -ot "$f" ]]; then
-            ((counter++))
-            infon "Converting [$counter/$num_newer_eps] ${bold}$f${normal} to ${bold}${f%\.*}.pdf${normal} ... "
-            # -dEPSCrop crops to figure. /prepress embeds fonts
-            ps2pdf -dPDFSETTINGS=/prepress -dEPSCrop "$f"
-            success $?
-        fi
-    done < <(find *.eps 2>/dev/null)
+    convert_eps_figures_to_pdf
     run_pdflatex "1st" || return
     if [[ "$BIBTEX" || "$INDEX" ]]; then
         [[ "$BIBTEX" ]]     && run_bibtex
@@ -1019,6 +1001,23 @@ compile_ps() {
 
 # Usage: compile_xelatex
 compile_xelatex() {
+    convert_eps_figures_to_pdf
+    run_xelatex "1st" || return
+    if [[ "$BIBTEX" || "$INDEX" ]]; then
+        [[ "$BIBTEX" ]]     && run_bibtex
+        [[ "$INDEX" ]]      && run_index
+        run_xelatex "2nd"  && run_xelatex "3rd"
+    elif [[ "$BIBLIOGRAPHY" || "$INDEX" ]]; then
+        # If it has come till here, then xelatex ran ok earlier
+        # So, we don't need to return on error
+        [[ "$INDEX" ]]      && run_index
+        run_xelatex "2nd"; run_xelatex "3rd"
+    fi
+}
+
+# If new *.eps figures are present, convert them to pdf before running either
+# pdflatex or xelatex
+convert_eps_figures_to_pdf() {
     local -i num_newer_eps=0
     local -i counter=0
     local f
@@ -1038,17 +1037,6 @@ compile_xelatex() {
             success $?
         fi
     done < <(find *.eps 2>/dev/null)
-    run_xelatex "1st" || return
-    if [[ "$BIBTEX" || "$INDEX" ]]; then
-        [[ "$BIBTEX" ]]     && run_bibtex
-        [[ "$INDEX" ]]      && run_index
-        run_xelatex "2nd"  && run_xelatex "3rd"
-    elif [[ "$BIBLIOGRAPHY" || "$INDEX" ]]; then
-        # If it has come till here, then xelatex ran ok earlier
-        # So, we don't need to return on error
-        [[ "$INDEX" ]]      && run_index
-        run_xelatex "2nd"; run_xelatex "3rd"
-    fi
 }
 
 # Whether index is to be generated or not.
